### ISSUE TITLE
CRUD Cliente

### ISSUE THREAD

**Issue by williamHatakeyama** [K-i-Q/Benefits#1]
- [x] Edit
- [x] Remove
- [x] Details
- [x] Create

**Criar ClienteDAO**

**Comment by K-i-Q** [comment]
Criado View, Action e método para cadastro de Cliente.

Commit: 6a506976759d6609b4e28f7c1526c223f6a05343

**Comment by K-i-Q** [comment]
Criado View, Action e método para edição de Cliente. Fiz uma alteração dentro da Classe de modelo de Cliente (passei o tipo da propriedade ClienteId de int para long) e o EF não deixou fazer Update-Database. A solução foi deletar o banco de dados e a pasta Migrations e criar novamente.

**Comment by K-i-Q** [comment]
Criado View e Action apenas para Detalhes do cliente. Pois utilizei o método já existente na Classe ClienteDAO para buscar o Cliente por Id.

**Comment by K-i-Q** [comment]
Criado View, Actions e método para exclusão do Cliente.
