### ISSUE TITLE
Criar _Layout

### ISSUE THREAD

**Issue by williamHatakeyama** [K-i-Q/Benefits#5]
- [x] Cabeçalho
- [x] Rodapé
- [x] Menu

**Comment by K-i-Q** [comment]
Foi definido o Layout com tema bootswatch. Cabeçalho, Menu e Rodapé estão criados para o Cliente. Dentro do menu já existe a navegação entre as Views. 

**Commit: _fdbde50253c9fd83d2ed41761b01cdd01db2d718_**
